CREATE TABLE IF NOT EXISTS audit_log (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    tenant_id BIGINT COMMENT '租户ID',
    project_id BIGINT COMMENT '项目ID',
    user_id BIGINT COMMENT '操作用户ID',
    user_name VARCHAR(64) COMMENT '操作用户名',
    operation VARCHAR(128) NOT NULL COMMENT '操作类型',
    target_type VARCHAR(64) COMMENT '目标类型',
    target_id BIGINT COMMENT '目标ID',
    before_data TEXT COMMENT '操作前数据',
    after_data TEXT COMMENT '操作后数据',
    detail VARCHAR(2048) COMMENT '操作详情',
    ip VARCHAR(64) COMMENT 'IP地址',
    user_agent VARCHAR(512) COMMENT 'UserAgent',
    request_id VARCHAR(64) COMMENT '请求ID',
    created_time DATETIME NOT NULL COMMENT '创建时间',
    INDEX idx_audit_tenant_id (tenant_id),
    INDEX idx_audit_project_id (project_id),
    INDEX idx_audit_user_id (user_id),
    INDEX idx_audit_created_time (created_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='审计日志表';